import type { Product } from '@/types';

/**
 * Demo products for local development without Supabase.
 * Remove this file and the mock fallback in page.tsx when connecting to a real database.
 */
export const DEMO_PRODUCTS: Product[] = [
  // ============================================
  // BURGERS
  // ============================================
  {
    id: 'demo-1',
    name: 'La Colesterol',
    description: 'Nuestra insignia. Doble carne, doble queso cheddar, bacon crocante, cebolla caramelizada y salsa secreta Colesterol.',
    price: 8.50,
    category: 'burgers',
    image_url: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&q=80',
    video_url: null,
    customizations: [
      {
        name: 'Término de carne',
        type: 'single',
        required: true,
        options: [
          { name: 'Medio', price: 0 },
          { name: 'Término medio', price: 0 },
          { name: 'Bien cocido', price: 0 },
        ],
      },
      {
        name: 'Extras',
        type: 'multiple',
        required: false,
        options: [
          { name: 'Tocineta extra', price: 1.50 },
          { name: 'Queso extra', price: 1.00 },
          { name: 'Guacamole', price: 1.50 },
        ],
      },
    ],
    ingredients_to_remove: ['cebolla', 'lechuga', 'tomate', 'bacon'],
    is_available: true,
    is_featured: true,
    sort_order: 1,
    prep_time_minutes: 12,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-2',
    name: 'Smash Burger',
    description: 'Carne smash a la plancha, queso Americano, pickles, cebolla fresca y special sauce.',
    price: 6.50,
    category: 'burgers',
    image_url: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=600&q=80',
    video_url: null,
    customizations: [
      {
        name: 'Término de carne',
        type: 'single',
        required: true,
        options: [
          { name: 'Medio', price: 0 },
          { name: 'Término medio', price: 0 },
          { name: 'Bien cocido', price: 0 },
        ],
      },
      {
        name: 'Extras',
        type: 'multiple',
        required: false,
        options: [
          { name: 'Doble carne', price: 3.00 },
          { name: 'Queso extra', price: 1.00 },
        ],
      },
    ],
    ingredients_to_remove: ['pickles', 'cebolla'],
    is_available: true,
    is_featured: true,
    sort_order: 2,
    prep_time_minutes: 10,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-3',
    name: 'BBQ Bacon Burger',
    description: 'Carne Angus, bacon, aros de cebolla, queso pepper jack y salsa BBQ ahumada.',
    price: 9.00,
    category: 'burgers',
    image_url: 'https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?w=600&q=80',
    video_url: null,
    customizations: [
      {
        name: 'Término de carne',
        type: 'single',
        required: true,
        options: [
          { name: 'Medio', price: 0 },
          { name: 'Término medio', price: 0 },
          { name: 'Bien cocido', price: 0 },
        ],
      },
    ],
    ingredients_to_remove: ['cebolla', 'bacon'],
    is_available: true,
    is_featured: false,
    sort_order: 3,
    prep_time_minutes: 12,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-4',
    name: 'Pollo Crispy',
    description: 'Pechuga de pollo empanizada, lechuga, tomate, mayonesa y pickles en bun brioche.',
    price: 7.00,
    category: 'burgers',
    image_url: 'https://images.unsplash.com/photo-1606756790138-261d2b101820?w=600&q=80',
    video_url: null,
    customizations: [
      {
        name: 'Salsa',
        type: 'single',
        required: false,
        options: [
          { name: 'Mayonesa', price: 0 },
          { name: 'BBQ', price: 0 },
          { name: 'Buffalo', price: 0.50 },
        ],
      },
    ],
    ingredients_to_remove: ['lechuga', 'tomate', 'pickles'],
    is_available: true,
    is_featured: false,
    sort_order: 4,
    prep_time_minutes: 10,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // ============================================
  // ENTRADAS
  // ============================================
  {
    id: 'demo-5',
    name: 'Loaded Fries',
    description: 'Papas fritas crocantes con queso cheddar derretido, bacon y chives.',
    price: 5.50,
    category: 'appetizers',
    image_url: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=600&q=80',
    video_url: null,
    customizations: [],
    ingredients_to_remove: [],
    is_available: true,
    is_featured: true,
    sort_order: 10,
    prep_time_minutes: 8,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-6',
    name: 'Onion Rings',
    description: 'Aros de cebolla empanizados con dip de queso cheddar.',
    price: 4.50,
    category: 'appetizers',
    image_url: 'https://images.unsplash.com/photo-1639024471283-03518883512d?w=600&q=80',
    video_url: null,
    customizations: [],
    ingredients_to_remove: [],
    is_available: true,
    is_featured: false,
    sort_order: 11,
    prep_time_minutes: 7,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-7',
    name: 'Chicken Wings',
    description: '6 alitas de pollo con salsa a elegir: BBQ, Buffalo o Honey Mustard.',
    price: 6.00,
    category: 'appetizers',
    image_url: 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?w=600&q=80',
    video_url: null,
    customizations: [
      {
        name: 'Salsa',
        type: 'single',
        required: true,
        options: [
          { name: 'BBQ', price: 0 },
          { name: 'Buffalo', price: 0 },
          { name: 'Honey Mustard', price: 0 },
        ],
      },
    ],
    ingredients_to_remove: [],
    is_available: true,
    is_featured: true,
    sort_order: 12,
    prep_time_minutes: 12,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // ============================================
  // ACOMPAÑAMIENTOS
  // ============================================
  {
    id: 'demo-8',
    name: 'Papas Fritas',
    description: 'Papas fritas crocantes con sal y seasoning especial.',
    price: 3.00,
    category: 'sides',
    image_url: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=600&q=80',
    video_url: null,
    customizations: [],
    ingredients_to_remove: [],
    is_available: true,
    is_featured: false,
    sort_order: 20,
    prep_time_minutes: 5,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // ============================================
  // BEBIDAS
  // ============================================
  {
    id: 'demo-9',
    name: 'Coca-Cola',
    description: 'Coca-Cola bien fría 355ml.',
    price: 1.50,
    category: 'drinks',
    image_url: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=600&q=80',
    video_url: null,
    customizations: [],
    ingredients_to_remove: [],
    is_available: true,
    is_featured: false,
    sort_order: 30,
    prep_time_minutes: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-10',
    name: 'Sprite',
    description: 'Sprite bien fría 355ml.',
    price: 1.50,
    category: 'drinks',
    image_url: 'https://images.unsplash.com/photo-1625772299848-391b6a87d7b3?w=600&q=80',
    video_url: null,
    customizations: [],
    ingredients_to_remove: [],
    is_available: true,
    is_featured: false,
    sort_order: 31,
    prep_time_minutes: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-11',
    name: 'Malta',
    description: 'Malta Regional bien fría.',
    price: 1.50,
    category: 'drinks',
    image_url: 'https://images.unsplash.com/photo-1581006852262-e4307cf6283a?w=600&q=80',
    video_url: null,
    customizations: [],
    ingredients_to_remove: [],
    is_available: true,
    is_featured: false,
    sort_order: 32,
    prep_time_minutes: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // ============================================
  // POSTRES
  // ============================================
  {
    id: 'demo-12',
    name: 'Brownie con Helado',
    description: 'Brownie de chocolate caliente con bola de helado de vainilla.',
    price: 4.50,
    category: 'desserts',
    image_url: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=600&q=80',
    video_url: null,
    customizations: [
      {
        name: 'Helado',
        type: 'single',
        required: true,
        options: [
          { name: 'Vainilla', price: 0 },
          { name: 'Chocolate', price: 0 },
          { name: 'Fresa', price: 0 },
        ],
      },
    ],
    ingredients_to_remove: [],
    is_available: true,
    is_featured: false,
    sort_order: 40,
    prep_time_minutes: 5,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // ============================================
  // COMBOS
  // ============================================
  {
    id: 'demo-13',
    name: 'Combo Colesterol',
    description: 'La Colesterol + Papas Fritas + Bebida. La experiencia completa.',
    price: 12.00,
    category: 'combos',
    image_url: 'https://images.unsplash.com/photo-1551782450-a2132b4ba21d?w=600&q=80',
    video_url: null,
    customizations: [
      {
        name: 'Término de carne',
        type: 'single',
        required: true,
        options: [
          { name: 'Medio', price: 0 },
          { name: 'Término medio', price: 0 },
          { name: 'Bien cocido', price: 0 },
        ],
      },
      {
        name: 'Bebida',
        type: 'single',
        required: true,
        options: [
          { name: 'Coca-Cola', price: 0 },
          { name: 'Sprite', price: 0 },
          { name: 'Malta', price: 0 },
          { name: 'Agua', price: 0 },
        ],
      },
    ],
    ingredients_to_remove: ['cebolla', 'lechuga', 'tomate'],
    is_available: true,
    is_featured: true,
    sort_order: 50,
    prep_time_minutes: 15,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-14',
    name: 'Combo Smash',
    description: 'Smash Burger + Loaded Fries + Bebida.',
    price: 10.50,
    category: 'combos',
    image_url: 'https://images.unsplash.com/photo-1561758033-d89a9ad46330?w=600&q=80',
    video_url: null,
    customizations: [
      {
        name: 'Bebida',
        type: 'single',
        required: true,
        options: [
          { name: 'Coca-Cola', price: 0 },
          { name: 'Sprite', price: 0 },
          { name: 'Malta', price: 0 },
        ],
      },
    ],
    ingredients_to_remove: [],
    is_available: true,
    is_featured: false,
    sort_order: 51,
    prep_time_minutes: 12,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
