import type { Order, OrderStatus } from '@/types';

/**
 * Demo orders for local development without Supabase.
 * These simulate real orders flowing through the system.
 */
export const DEMO_ORDERS: Order[] = [
  {
    id: 'demo-order-1',
    order_number: 1001,
    customer_name: 'Carlos Mendoza',
    customer_phone: '+58 414 123 4567',
    customer_lat: null,
    customer_lng: null,
    customer_address: 'Av. Principal, Caracas',
    customer_notes: 'Sin cebolla por favor',
    items: [
      {
        product_id: 'demo-1',
        name: 'La Colesterol',
        quantity: 2,
        unit_price: 8.50,
        total_price: 17.00,
        customizations: { 'Término de carne': 'Medio', 'Extras': ['Tocineta extra'] },
        removed_ingredients: ['cebolla'],
        notes: '',
      },
      {
        product_id: 'demo-9',
        name: 'Coca-Cola',
        quantity: 2,
        unit_price: 1.50,
        total_price: 3.00,
        customizations: {},
        removed_ingredients: [],
        notes: '',
      },
    ],
    subtotal: 20.00,
    delivery_fee: 2.00,
    total: 22.00,
    payment_method: 'cash_usd',
    payment_confirmed: true,
    status: 'received',
    assigned_driver_id: null,
    estimated_delivery_time: null,
    actual_delivery_time: null,
    kitchen_started_at: null,
    kitchen_ready_at: null,
    dispatched_at: null,
    delivered_at: null,
    cancelled_at: null,
    cancellation_reason: null,
    created_at: new Date(Date.now() - 3 * 60000).toISOString(), // 3 min ago
    updated_at: new Date(Date.now() - 3 * 60000).toISOString(),
  },
  {
    id: 'demo-order-2',
    order_number: 1002,
    customer_name: 'María González',
    customer_phone: '+58 412 987 6543',
    customer_lat: null,
    customer_lng: null,
    customer_address: 'Urb. Las Mercedes, Caracas',
    customer_notes: '',
    items: [
      {
        product_id: 'demo-2',
        name: 'Smash Burger',
        quantity: 1,
        unit_price: 6.50,
        total_price: 6.50,
        customizations: { 'Término de carne': 'Término medio' },
        removed_ingredients: [],
        notes: 'Extra salsa por favor',
      },
      {
        product_id: 'demo-5',
        name: 'Loaded Fries',
        quantity: 1,
        unit_price: 5.50,
        total_price: 5.50,
        customizations: {},
        removed_ingredients: [],
        notes: '',
      },
    ],
    subtotal: 12.00,
    delivery_fee: 2.00,
    total: 14.00,
    payment_method: 'pago_movil',
    payment_confirmed: true,
    status: 'preparing',
    assigned_driver_id: null,
    estimated_delivery_time: null,
    actual_delivery_time: null,
    kitchen_started_at: new Date(Date.now() - 8 * 60000).toISOString(),
    kitchen_ready_at: null,
    dispatched_at: null,
    delivered_at: null,
    cancelled_at: null,
    cancellation_reason: null,
    created_at: new Date(Date.now() - 10 * 60000).toISOString(),
    updated_at: new Date(Date.now() - 8 * 60000).toISOString(),
  },
  {
    id: 'demo-order-3',
    order_number: 1003,
    customer_name: 'Andrés López',
    customer_phone: '+58 416 555 1234',
    customer_lat: null,
    customer_lng: null,
    customer_address: 'Miraflores, Caracas',
    customer_notes: 'Apartamento 4B, timbre rojo',
    items: [
      {
        product_id: 'demo-13',
        name: 'Combo Colesterol',
        quantity: 1,
        unit_price: 12.00,
        total_price: 12.00,
        customizations: { 'Término de carne': 'Bien cocido', 'Bebida': 'Malta' },
        removed_ingredients: ['lechuga'],
        notes: '',
      },
    ],
    subtotal: 12.00,
    delivery_fee: 2.00,
    total: 14.00,
    payment_method: 'cash_usd',
    payment_confirmed: true,
    status: 'ready',
    assigned_driver_id: null,
    estimated_delivery_time: null,
    actual_delivery_time: null,
    kitchen_started_at: new Date(Date.now() - 20 * 60000).toISOString(),
    kitchen_ready_at: new Date(Date.now() - 5 * 60000).toISOString(),
    dispatched_at: null,
    delivered_at: null,
    cancelled_at: null,
    cancellation_reason: null,
    created_at: new Date(Date.now() - 25 * 60000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 60000).toISOString(),
  },
  {
    id: 'demo-order-4',
    order_number: 1004,
    customer_name: 'Laura Fernández',
    customer_phone: '+58 424 888 9999',
    customer_lat: null,
    customer_lng: null,
    customer_address: 'Los Palos Grandes, Caracas',
    customer_notes: '',
    items: [
      {
        product_id: 'demo-7',
        name: 'Chicken Wings',
        quantity: 2,
        unit_price: 6.00,
        total_price: 12.00,
        customizations: { 'Salsa': 'Buffalo' },
        removed_ingredients: [],
        notes: 'Bien picantes',
      },
      {
        product_id: 'demo-10',
        name: 'Sprite',
        quantity: 2,
        unit_price: 1.50,
        total_price: 3.00,
        customizations: {},
        removed_ingredients: [],
        notes: '',
      },
    ],
    subtotal: 15.00,
    delivery_fee: 2.00,
    total: 17.00,
    payment_method: 'zelle',
    payment_confirmed: true,
    status: 'dispatched',
    assigned_driver_id: 'demo-driver-1',
    estimated_delivery_time: new Date(Date.now() + 15 * 60000).toISOString(),
    actual_delivery_time: null,
    kitchen_started_at: new Date(Date.now() - 30 * 60000).toISOString(),
    kitchen_ready_at: new Date(Date.now() - 15 * 60000).toISOString(),
    dispatched_at: new Date(Date.now() - 12 * 60000).toISOString(),
    delivered_at: null,
    cancelled_at: null,
    cancellation_reason: null,
    created_at: new Date(Date.now() - 35 * 60000).toISOString(),
    updated_at: new Date(Date.now() - 12 * 60000).toISOString(),
  },
  {
    id: 'demo-order-5',
    order_number: 1005,
    customer_name: 'Pedro Ramírez',
    customer_phone: '+58 414 777 3333',
    customer_lat: null,
    customer_lng: null,
    customer_address: 'Altamira, Caracas',
    customer_notes: '',
    items: [
      {
        product_id: 'demo-3',
        name: 'BBQ Bacon Burger',
        quantity: 1,
        unit_price: 9.00,
        total_price: 9.00,
        customizations: { 'Término de carne': 'Medio' },
        removed_ingredients: [],
        notes: '',
      },
      {
        product_id: 'demo-8',
        name: 'Papas Fritas',
        quantity: 1,
        unit_price: 3.00,
        total_price: 3.00,
        customizations: {},
        removed_ingredients: [],
        notes: '',
      },
    ],
    subtotal: 12.00,
    delivery_fee: 2.00,
    total: 14.00,
    payment_method: 'cash_ves',
    payment_confirmed: true,
    status: 'on_the_way',
    assigned_driver_id: 'demo-driver-1',
    estimated_delivery_time: new Date(Date.now() + 5 * 60000).toISOString(),
    actual_delivery_time: null,
    kitchen_started_at: new Date(Date.now() - 40 * 60000).toISOString(),
    kitchen_ready_at: new Date(Date.now() - 20 * 60000).toISOString(),
    dispatched_at: new Date(Date.now() - 18 * 60000).toISOString(),
    delivered_at: null,
    cancelled_at: null,
    cancellation_reason: null,
    created_at: new Date(Date.now() - 45 * 60000).toISOString(),
    updated_at: new Date(Date.now() - 18 * 60000).toISOString(),
  },
  {
    id: 'demo-order-6',
    order_number: 1006,
    customer_name: 'Sofía Torres',
    customer_phone: '+58 412 111 2222',
    customer_lat: null,
    customer_lng: null,
    customer_address: 'Chacao, Caracas',
    customer_notes: 'Timbre 3',
    items: [
      {
        product_id: 'demo-14',
        name: 'Combo Smash',
        quantity: 1,
        unit_price: 10.50,
        total_price: 10.50,
        customizations: { 'Bebida': 'Coca-Cola' },
        removed_ingredients: [],
        notes: '',
      },
      {
        product_id: 'demo-12',
        name: 'Brownie con Helado',
        quantity: 1,
        unit_price: 4.50,
        total_price: 4.50,
        customizations: { 'Helado': 'Chocolate' },
        removed_ingredients: [],
        notes: '',
      },
    ],
    subtotal: 15.00,
    delivery_fee: 2.00,
    total: 17.00,
    payment_method: 'cash_usd',
    payment_confirmed: true,
    status: 'delivered',
    assigned_driver_id: 'demo-driver-1',
    estimated_delivery_time: null,
    actual_delivery_time: new Date(Date.now() - 5 * 60000).toISOString(),
    kitchen_started_at: new Date(Date.now() - 50 * 60000).toISOString(),
    kitchen_ready_at: new Date(Date.now() - 35 * 60000).toISOString(),
    dispatched_at: new Date(Date.now() - 30 * 60000).toISOString(),
    delivered_at: new Date(Date.now() - 5 * 60000).toISOString(),
    cancelled_at: null,
    cancellation_reason: null,
    created_at: new Date(Date.now() - 55 * 60000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 60000).toISOString(),
  },
];
